[WIP] OT198-41 Endpoint Category List
alkemyTech/OT198-Server pull request #12
Opened 2022-05-24 21:50 UTC by honeybadger2788

## Description

AS a admin user
I WANT TO get the categories list
SO THAT I can manage categories

### Acceptance criteria
GET to /categories. It will return the categories list. It should just return the category's name attribute.

2022-05-24 23:41 UTC, nicobes14 submitted a review, later dismissed
Muy bueno Noe!

2022-05-25 13:24 UTC, gabodmc requested changes
Excelente PR. Muy bien expuesta la evidencia. Solo una correción

2022-05-25 13:24 UTC, gabodmc commented on controllers/categories.js
> +      const categories = await Category.findAll({ attributes: ['name'] })
delegar las funcionalidades de la db al servicio

2022-05-25 15:33 UTC, nicobes14 approved these changes

2022-05-25 16:43 UTC, gabodmc approved these changes

2022-05-25 17:51 UTC, HernanGarcia1985 approved these changes

2022-05-25 17:53 UTC, HernanGarcia1985 approved these changes
Muy bueno!

2022-05-25 18:07 UTC, merged