[ENDPOINT] - Get /categories/:id Endpoint Detail Category - OT198-42
alkemyTech/OT198-Server pull request #13
Opened 2022-05-25 14:01 UTC by nicobes14

[OT198-42](https://alkemy-labs.atlassian.net/browse/OT198-42)
## Description

AS admin user
I WANT to obtain information on an individual category
TO be able to manage it

### Criteria of acceptance:
GET to /categories/:id . It will show all the fields of a category based on the id sent by parameter. In the event that it does not exist, it will return an error with a 404 status code

### Evidence
- GET to /categories/:id success
![image](https://user-images.githubusercontent.com/88128116/170483626-7ef51974-0c6e-414b-863d-8ecad836aab4.png)
- GET to /categories/:id category not found
![image](https://user-images.githubusercontent.com/88128116/170484662-c9f70b2d-47ed-4b0e-9e7a-c35b0dc65418.png)
- GET to /categories/:id when the problem is with the database the error is triggered by the service
![image](https://user-images.githubusercontent.com/88128116/170487269-0197a35a-a616-4ed9-8829-7fa312c0c17f.png)

## Fixes
- delete id from activity model 
![image](https://user-images.githubusercontent.com/88128116/170393473-a82b9829-807d-40b1-96b6-5332e0f48bec.png)
- add association in categories model
![image](https://user-images.githubusercontent.com/88128116/170393621-2fac8df0-1b67-4a91-a09e-87531d720997.png)
- making the association as it says in the sequelize documentation in new model
![image](https://user-images.githubusercontent.com/88128116/170393811-ac938660-3ba9-4274-ac3c-e94e2bb86e35.png)
- same as above
![image](https://user-images.githubusercontent.com/88128116/170393875-cd1b3760-be81-4757-8dde-ae034198e083.png)
- rename new migration to be after categories migration and add association
![image](https://user-images.githubusercontent.com/88128116/170394134-9a16dca8-05c0-422b-974c-7bc247e1fef9.png)
- making the user email unique as requested by the card
![image](https://user-images.githubusercontent.com/88128116/170394350-766c64e9-a61a-4864-9c76-a488556838c5.png)

2022-05-25 14:33 UTC, gabodmc approved these changes
Solo unas correciones. El pr en general esta bien

2022-05-25 14:33 UTC, gabodmc commented on controllers/activity.js
> +}
Entiendo que fue una corrección del lint, pero guarda con subir cambios que no corresponden al scope de la card. Hay que consultar quien subio esto con el error de identacion y corregirlo en un fix

2022-05-25 14:34 UTC, gabodmc requested changes
Solo unas correciones.

2022-05-25 21:12 UTC, honeybadger2788 requested changes
Revisar orden de rutas

2022-05-25 21:12 UTC, honeybadger2788 commented on routes/categories.js
> +router.get('/:id', getCategory)
Ojo! la ruta con el /:id creo que debería ir antes que la ruta / porque sino puede traer error

2022-05-26 00:45 UTC, honeybadger2788 approved these changes
Gracias, Nico!!!!

2022-05-26 00:48 UTC, penalvapablo approved these changes

2022-05-26 12:51 UTC, HernanGarcia1985 approved these changes
Todo ok! Se modifican de acuerdo a los comentarios.
También se corrigen varios errores en otros modelos, bien detallados los cambios. Gracias!!!

2022-05-26 12:52 UTC, gabodmc approved these changes
Buenas correciones!

2022-05-26 12:55 UTC, merged