[CATEGORY] -  Endpoint Creation Categories - OT198-43
alkemyTech/OT198-Server pull request #17
Opened 2022-05-26 14:02 UTC by nicobes14

[OT198-43](https://alkemy-labs.atlassian.net/browse/OT198-43)
## Description

AS admin user
I WANT to add a new category to the system
TO categorize the News

### Criteria of acceptance:
POST /categories - You must validate that the name field is sent, and it is a string
## Evidence
- POST /categories with name as string
![image](https://user-images.githubusercontent.com/88128116/170502819-e3206966-3531-448e-be13-bd96505c9c00.png)
- POST /categories with name as not string
![image](https://user-images.githubusercontent.com/88128116/170503103-4491860e-1947-491e-991a-625dd3a948dd.png)
- POST /categories without params
![image](https://user-images.githubusercontent.com/88128116/170503278-0aeb5b8b-0df4-4d54-899e-43c69ca167e1.png)

2022-05-26 14:15 UTC, honeybadger2788 commented on controllers/categories.js
> +      const { name, description, image } = req.body
Sugerencia... yo suelo poner validationResult(req).throw() dentro del try para evitar el IF

2022-05-26 14:17 UTC, gabodmc requested changes

2022-05-26 14:17 UTC, gabodmc commented on controllers/categories.js
> +  if (validationResult(req).isEmpty()) {
Trabajar el manejo de errores dentro de un middleware

2022-05-26 14:17 UTC, gabodmc commented on routes/categories.js
> +router.post('/', body('name').isString().notEmpty().trim(), create)
trabajar dentro de un schema para categories

2022-05-26 14:17 UTC, gabodmc commented on controllers/categories.js
> +const create = async (req, res, next) => {
"const post" creo que seria mejor

2022-05-26 14:22 UTC, honeybadger2788 commented on routes/categories.js
> +router.post('/', body('name').isString().notEmpty().trim(), create)
Sugerencia...Poner el .trim() primero por si se insertan solo espacios

2022-05-26 19:16 UTC, honeybadger2788 commented on services/categories.js
> +    const newCategory = await Category.create(category)
Pregunta: No convendría utilizar findAndCreate como para validar que si ya existe, no la vuelve a crear?

2022-05-26 22:52 UTC, honeybadger2788 approved these changes
Buenisimo, Nico!

2022-05-26 23:00 UTC, Nicolasq57 approved these changes
buen manejo del schema nico!

2022-05-27 12:18 UTC, gabodmc approved these changes
Muy buen PR Nico! Me gusto ese codigo 201 en la respuesta de creacion

2022-05-27 12:43 UTC, merged