[SLIDES] - Endpoint List Slides - OT198-57
alkemyTech/OT198-Server pull request #19
Opened 2022-05-26 22:30 UTC by Nicolasq57

Descripción

COMO usuario administrador
QUIERO ver el listados de Slides
PARA ver el contenido de forma gráfica.

Criterios de aceptación:

Se debe hacer una petición GET a /Slides. 

Devolverá el listado de Slides, con la miniatura y el orden del mismo

2022-05-26 23:00 UTC, honeybadger2788 requested changes
Algunos comentarios

2022-05-26 23:00 UTC, honeybadger2788 commented on services/slide.js
> +        ],
Entiendo que la card no pide un orden especifico sino que devuelva el campo order

2022-05-26 23:17 UTC, Nicolasq57 commented on services/slide.js
> +        ],
habia entendido algo distinto en la card pero tenes razon noe, gracias por la observacion. Ahi van los changes

2022-05-26 23:21 UTC, honeybadger2788 approved these changes
Excelente, Nico!

2022-05-27 02:15 UTC, nicobes14 approved these changes
Muy bueno Fran!

2022-05-27 12:14 UTC, gabodmc approved these changes
Muy bueno Fran! Pero recorda poner la evidencia de caso de response 200 y los casos de error asi se ve el resultado de tu endpoint.

2022-05-27 13:41 UTC, merged