create model activities and migration
alkemyTech/OT198-Server pull request #2
Opened 2022-05-20 19:38 UTC by Nicolasq57

![Captura de pantalla 2022-05-20 163655](https://user-images.githubusercontent.com/88246144/169599663-88a97e75-3570-4460-8113-75efa9876a77.jpg)
table activities

2022-05-20 20:49 UTC, gabodmc requested changes

2022-05-20 20:49 UTC, gabodmc commented on database/models/activities.js
> +    modelName: 'Activities',
agregar timestamps

2022-05-21 15:42 UTC, nicobes14 commented on .eslintignore
> +.env
Aunque esto no creo que rompa nada, creo que no deberiamos agregar estos archivos a los commit.

2022-05-21 15:44 UTC, nicobes14 commented on .gitignore
> +package.json
```suggestion
```
Siguiendo lo comentado por gabo en otro pr, no deberiamos agregar el package.json al git ignore

2022-05-21 15:49 UTC, nicobes14 commented on database/config/config.js
> +};
El archivo de configuracion es distinto al de la rama main, quizas con hacer un pull a la rama main se actualice, no estoy seguro

2022-05-21 15:54 UTC, nicobes14 reviewed
Nico, en tu card te pide que hagas el modelo y la migracion, pero tambien el controlador base que estaria faltando, o vas a hacer otro pr para esa parte? Por lo que entendi yo, cada pr deberia resolver una card

2022-05-21 19:58 UTC, Nicolasq57 commented
> Nico, en tu card te pide que hagas el modelo y la migracion, pero tambien el controlador base que estaria faltando, o vas a hacer otro pr para esa parte? Por lo que entendi yo, cada pr deberia resolver una card

nico, como ayer gabo te habia dicho que el controller estaba fuera del scope de la tarea no lo habia echo, pero ahora agrego el controller base como las otras pr

2022-05-23 18:14 UTC, gabodmc requested changes

2022-05-23 18:14 UTC, gabodmc commented on .eslintignore
> +.env
no modificar estos archivos de lint a menos que sea necesario y sea consensuado con el equipo.

2022-05-23 21:08 UTC, gabodmc requested changes

2022-05-23 21:08 UTC, gabodmc commented on package.json
> +    "mysql2": "^2.3.3",
Sigo viendo los cambios de version en el package.

2022-05-23 21:24 UTC, Nicolasq57 commented on package.json
> +    "mysql2": "^2.3.3",
habia hecho un pull y pense que se habia corregido. ahi estaria

2022-05-23 23:48 UTC, gabodmc approved these changes
Buen PR!

2022-05-24 00:11 UTC, nicobes14 approved these changes

2022-05-24 00:17 UTC, nicobes14 commented on database/models/activities.js
> +  class Activities extends Model {
```suggestion
  class Activitie extends Model {
```

2022-05-24 00:17 UTC, nicobes14 commented on database/models/activities.js
> +  Activities.init({
```suggestion
  Activitie.init({
```

2022-05-24 00:18 UTC, nicobes14 commented on database/models/activities.js
> +    modelName: 'Activities',
```suggestion
    modelName: 'Activitie',
```

2022-05-24 00:18 UTC, nicobes14 commented on database/models/activities.js
> +  return Activities;
```suggestion
  return Activitie;
```

2022-05-24 00:19 UTC, nicobes14 commented on controllers/activities.js
> +const { Activities } = db
```suggestion
const { Activitie } = db
```

2022-05-24 00:19 UTC, nicobes14 commented on controllers/activities.js
> +        const activities = await Activities.findAll()
```suggestion
        const activities = await ActivitiesfindAll()
```

2022-05-24 00:20 UTC, nicobes14 requested changes
en base a lo que comento gabo, cambiar el nombre de los archivos a singular

2022-05-24 01:11 UTC, gabodmc requested changes
bajar el modelo activities y crear nuevo modelo Activity. No modificar a mano

2022-05-24 01:11 UTC, gabodmc commented on controllers/activities.js
> +const { Activities } = db
Acivity en lugar de Activitie

2022-05-24 02:17 UTC, Nicolasq57 commented
tuve algunos inconvenientes con el pusheo, al final logre forzarlo. Entendi que no es la opcion mas viable pero fue la unica que me funciono. Quedo atento a recomendaciones.

2022-05-24 14:28 UTC, honeybadger2788 commented on database/migrations/20220524011902-create-activity.js
> +      },
Falta agregar los not null en los campos name, image y content

2022-05-24 18:43 UTC, gabodmc approved these changes

2022-05-24 19:45 UTC, penalvapablo approved these changes

2022-05-24 19:55 UTC, honeybadger2788 reviewed
Todo ok!

2022-05-24 19:56 UTC, honeybadger2788 approved these changes
Todo ok!

2022-05-24 20:39 UTC, nicobes14 approved these changes

2022-05-24 20:41 UTC, merged