[LOGIN] - Authentication Endpoint - OT198-25
alkemyTech/OT198-Server pull request #25
Opened 2022-05-27 18:45 UTC by nicobes14

[OT198-25](https://alkemy-labs.atlassian.net/browse/OT198-25)
## Description
AS user
I WANT to log into the system
TO access its functionalities

### Criteria of acceptance:

- A request of type POST /auth/login must be made
- The sending of the email and password fields in the request must be validated, and the password must be decrypted to authenticate
- Validate email and password on request
- Check if there is a user with the requested email
- If exists, compare encrypted password with password sent on request
- Return the user if it exists and the password is valid, if an error occurs, return {ok: false}
### Evidence
- happy path
![image](https://user-images.githubusercontent.com/88128116/170771391-d9f273fb-05ee-4211-ad09-43f52dc9f49b.png)
- missing arguments
![image](https://user-images.githubusercontent.com/88128116/170771536-8ae966ff-5d7a-4d61-8815-4e63469bc28a.png)
- user not found or incorrect password
![image](https://user-images.githubusercontent.com/88128116/170771664-0c7b1526-1eb4-42be-bbf0-78b96eddb8f2.png)

2022-05-27 19:09 UTC, honeybadger2788 approved these changes
Excelente, Nico

2022-05-27 19:35 UTC, gabodmc requested changes
Algunas correciones para hacerle

2022-05-27 19:35 UTC, gabodmc commented on services/user.js
> +      const user = await User.findOne({ where: { email } })
usar el id como identificador de usuario

2022-05-27 19:35 UTC, gabodmc commented on services/user.js
> +  tryLogin: async ({ email, password }) => {
aca usaria un getUserById o algo por el estilo. Este nombre no esta muy relacionado a lo que hace el servicio

2022-05-27 19:35 UTC, gabodmc commented on services/user.js
> +          message: 'User not found or password incorrect',
cambiar por "invalid credentials" para no dar mucha explicacion de lo que falló

2022-05-27 20:36 UTC, JoaquinBar1 approved these changes
Muy bueno Nico!

2022-05-27 21:34 UTC, JoaquinBar1 approved these changes

2022-05-28 15:44 UTC, gabodmc approved these changes
Genial Nico!

2022-05-28 15:46 UTC, merged