[ROLES] - Ot198-16 Create Roles model, migration and controller
alkemyTech/OT198-Server pull request #4
Opened 2022-05-20 23:09 UTC by penalvapablo

[Ot198-16](https://alkemy-labs.atlassian.net/browse/OT198-16)
## Description:

### Model fields:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
description: VARCHAR NULLABLE
timestamps

### Roles controller

## Evidence:

![image](https://user-images.githubusercontent.com/81152540/169622961-15b63274-3921-47bf-9694-c3bdaa1022fb.png)

2022-05-20 23:30 UTC, nicobes14 reviewed
Al eliminar el .env.example y hacer el merge no se va a borrar en la rama main ?

2022-05-21 01:54 UTC, nicobes14 approved these changes
Genial Pablo

2022-05-21 13:17 UTC, gabodmc requested changes
Todo muy bien, salvo

2022-05-21 13:17 UTC, gabodmc commented on .gitignore
> +package.json
No agregar el package.json al ignore, sino cuando instalen dependencias para el proyecto nunca se van a subir.

2022-05-21 13:17 UTC, gabodmc commented on .env.example
> +DB_PORT=3306
Este archivo no va a molestar en nada, pero esten atentos cuando hacen un git add para no subir cosas que no tienen que subir.

2022-05-23 15:48 UTC, honeybadger2788 approved these changes
Todo ok!

2022-05-23 18:26 UTC, gabodmc approved these changes
Bien esas correciones. Buen PR!

2022-05-23 19:26 UTC, merged