[USERS]OT198-17 MODELS, MIGRATE AND CONTROLLER.
alkemyTech/OT198-Server pull request #7
Opened 2022-05-23 22:07 UTC by JoaquinBar1

[OT198-17](https://alkemy-labs.atlassian.net/browse/OT198-17)

## DESCRIPTION 

id: INTEGER NOT NULL AUTO_INCREMENT
firstName: VARCHAR NOT NULL
lastName: VARCHAR NOT NULL
email: VARCHAR UNIQUE NOT NULL
password: VARCHAR NOT NULL
photo: VARCHAR NULLABLE
roleId: foreignKey for ID from Role
timestamps y softDeletes

### EVIDENCE 

<img width="681" alt="Captura de Pantalla 2022-05-23 a la(s) 18 53 28" src="https://user-images.githubusercontent.com/86156941/169912919-23aa9473-50fd-446b-9113-65ced3a2a39b.png">

2022-05-23 22:12 UTC, nicobes14 approved these changes
Todo ok! muy bueno Joaquin.

2022-05-23 22:17 UTC, honeybadger2788 requested changes
Fijate que segun tu tarjeta, el unico campo que acepta NULL es el de photo

2022-05-23 23:50 UTC, gabodmc approved these changes
Muy bueno. Recordar la asociacion desde Roles

2022-05-23 23:52 UTC, gabodmc requested changes
Recordar que los modelos son siempre en singular (User, Role, etc)

2022-05-23 23:52 UTC, gabodmc commented on controllers/users.js
> +    const User = await Users.findAll()
Los modelos son en singular

2022-05-24 15:09 UTC, HernanGarcia1985 commented on database/migrations/20220523145145-create-users.js
> +      }
Creo que faltaría el campo deletedAt para el soft delete

2022-05-24 18:48 UTC, gabodmc approved these changes
Buen fix !

2022-05-24 19:35 UTC, Nicolasq57 approved these changes
todo ok

2022-05-24 20:40 UTC, merged