[NEWS] Ot198-19 - Create Model Migration and News Base Controller
alkemyTech/OT198-Server pull request #8
Opened 2022-05-23 22:20 UTC by maxisosa89

[OT198-19](https://alkemy-labs.atlassian.net/browse/OT198-19)

## Description:

- Model fields:

id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
categoryId: Clave foranea hacia ID de Categories
timestamps y softDeletes

- News controller

## Evidence:

After run `$ sequelize-cli db:migrate`

![image](https://user-images.githubusercontent.com/82429592/169913947-c32e04e5-2a50-48d2-949b-301d97d7f2ab.png)

![image](https://user-images.githubusercontent.com/82429592/169913967-15666f6e-8115-4a05-bcc7-1b1da10e890e.png)

2022-05-23 22:34 UTC, nicobes14 commented on controllers/new.js
> +    res.send(allNews)
Esta bien el controlador pero podrias utilizar los helpers como los demas controladores para que queden todos iguales.

2022-05-23 22:36 UTC, nicobes14 commented on database/migrations/20220523185715-create-new.js
> +      }
falta el campo deletedAt y los allowNull en false como lo pide la card

2022-05-23 22:40 UTC, nicobes14 commented on database/models/new.js
> +    modelName: 'New',
falta el timestamps y el softDelete (paranoid)

2022-05-23 22:41 UTC, nicobes14 requested changes
los cambios al controlador no creo que sean relevantes, pero si los cambios al modelo y la migracion

2022-05-23 22:41 UTC, Nicolasq57 commented on database/models/new.js
> +    modelName: 'New',
avisa cualquier cosa si necesitas una mano para solucionarlo

2022-05-23 22:45 UTC, nicobes14 commented on database/models/new.js
> +      // define association here
falta la asociacion con el id de categories, (falta que juan suba el modelo)

2022-05-23 23:45 UTC, gabodmc commented on controllers/new.js
> +    res.send(allNews)
no hace falta a esta altura el helper, total van a tener que reconstruirlo cuando tengan que hacer el endpoint

2022-05-23 23:46 UTC, gabodmc requested changes

2022-05-23 23:46 UTC, gabodmc commented on database/migrations/20220523185715-create-new.js
> +      }
+1

2022-05-23 23:46 UTC, gabodmc commented on database/models/new.js
> +      // define association here
Idem Nico. Tambien desde el otro lado hay que asociarlo.

2022-05-23 23:46 UTC, gabodmc commented on database/models/new.js
> +    modelName: 'New',
+1

2022-05-24 13:41 UTC, maxisosa89 commented on controllers/new.js
> +    res.send(allNews)
De acuerdo a lo que indica @gabodmc, no se modifica.

2022-05-24 13:41 UTC, maxisosa89 commented on database/models/new.js
> +    modelName: 'New',
Agregados

2022-05-24 13:42 UTC, maxisosa89 commented on database/models/new.js
> +      // define association here
Quedo a la espera de que suba el modelo de categories para asociarlo

2022-05-24 14:39 UTC, HernanGarcia1985 approved these changes

2022-05-24 18:45 UTC, gabodmc approved these changes

2022-05-24 18:46 UTC, gabodmc approved these changes

2022-05-24 19:35 UTC, Nicolasq57 approved these changes
todo ok

2022-05-24 20:40 UTC, nicobes14 approved these changes

2022-05-24 20:43 UTC, merged