[PAGINATION] OT198-85 - Add pagination to categories, update pagination method to make de url dynamic and fix de list members with the new pagination
alkemyTech/OT198-Server pull request #93
Opened 2022-06-10 19:39 UTC by HernanGarcia1985

[OT198-85](https://alkemy-labs.atlassian.net/browse/OT198-85)

## **Description:**

COMO usuario
QUIERO visualizar los resultados de Categorías paginados
PARA aumentar la velocidad de respuesta

Criterios de aceptación:
Cuando se realice la petición para listar, los resultados deberán paginarse de a 10. En la respuesta, se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden). La página actual se obtendrá del parámetro de query ?page

## **Evidance:**

Success:
![85 - Endpoint get categories page 1 success](https://user-images.githubusercontent.com/85139674/173137737-9426ce33-7000-4085-9c72-f4c32edc0a75.png)
![85 - Endpoint get categories page 2 success](https://user-images.githubusercontent.com/85139674/173137793-f1946ae9-7216-42db-85a3-9e211afa7541.png)
![85 - Endpoint get categories page last (3) success](https://user-images.githubusercontent.com/85139674/173137828-857dde4d-1374-482e-90de-4fd749f9a94f.png)

Members succcess too:
![85 - Endpoint get members page 1 success](https://user-images.githubusercontent.com/85139674/173137868-f0e62c12-2ff6-44e3-a26a-0d290958e1dd.png)

2022-06-13 15:28 UTC, gabodmc requested changes
Podrias poner en la evidencia que pasa cuando liste los miembros y la tabla no contenga datos?

2022-06-13 17:40 UTC, HernanGarcia1985 commented
> Podrias poner en la evidencia que pasa cuando liste los miembros y la tabla no contenga datos?

Lo pongo acá abajo como se ve, se podría normalizar el error Not found 404 como a otros servicios (sólo q en la card de listar, antes de la paginación, no lo pedía)
![85 - Endpoint get members empty array](https://user-images.githubusercontent.com/85139674/173411931-bb1050ad-1b6d-4813-9c39-807d03126344.png)

2022-06-14 13:15 UTC, gabodmc approved these changes

2022-06-14 14:20 UTC, JoaquinBar1 approved these changes

2022-06-14 18:07 UTC, merged